// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwgxodjfuogwmcmjkaez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Z3hvZGpmdW9nd21jbWprYWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTkyODMsImV4cCI6MjA2MjYzNTI4M30.r_ATrtsyIhW2cXUoXEP_aUGPdQTxWHA7oPSJT8m8fhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);