// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhiasluiscvfhswnbzfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oaWFzbHVpc2N2Zmhzd25iemZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTc3NTMsImV4cCI6MjA2MTc5Mzc1M30.NdeJF_QhRbbPm9j-OnFL8EJlzFvPJf-0JrpakunlIq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);